import { createClient } from "@/lib/supabase/server";
import { publishEvent } from "./events";

export interface PlaybookStepConfig {
  endpoint?: string;
  description?: string;
  role?: string;
  title?: string;
}

/**
 * Playbook Engine manages standard operating procedures (SOPs), triggers playbook runs,
 * handles approval checkpoints, and logs the execution success score.
 */
export async function triggerPlaybook(
  playbookId: string,
  triggeredBy: string
): Promise<{ success: boolean; executionId?: string; error?: string }> {
  const supabase = await createClient();

  // 1. Fetch playbook
  const { data: playbook, error: pbErr } = await supabase
    .from("playbooks")
    .select("*")
    .eq("id", playbookId)
    .maybeSingle();

  if (pbErr || !playbook) {
    return { success: false, error: `Playbook not found: ${pbErr?.message || 'unknown'}` };
  }

  // 2. Create execution entry
  const expectedOutcomeStr = `Resolve metric breach for ${playbook.name}`;
  const { data: execution, error: execErr } = await supabase
    .from("playbook_executions")
    .insert({
      playbook_id: playbookId,
      status: "suggested",
      current_step: 1,
      triggered_by: triggeredBy,
      expected_outcome: expectedOutcomeStr
    })
    .select("id")
    .single();

  if (execErr || !execution) {
    return { success: false, error: `Failed to create playbook execution: ${execErr?.message}` };
  }

  await publishEvent("PLAYBOOK_TRIGGERED", "playbook", playbookId, {
    execution_id: execution.id,
    playbook_name: playbook.name
  }, "operations");

  return { success: true, executionId: execution.id };
}

/**
 * Approves a suggested/pending playbook execution and starts running its steps.
 */
export async function approvePlaybook(
  executionId: string,
  approvedBy: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  // 1. Fetch execution
  const { data: execution, error: execErr } = await supabase
    .from("playbook_executions")
    .select("*")
    .eq("id", executionId)
    .maybeSingle();

  if (execErr || !execution) {
    return { success: false, error: `Execution not found: ${execErr?.message}` };
  }

  // Update status to approved and running
  await supabase
    .from("playbook_executions")
    .update({
      status: "running",
      approved_by: approvedBy,
      approved_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    })
    .eq("id", executionId);

  await publishEvent("PLAYBOOK_APPROVED", "playbook_execution", executionId, {
    playbook_id: execution.playbook_id,
    approved_by: approvedBy
  }, "operations");

  // Run steps from current step
  return runPlaybookSteps(executionId);
}

/**
 * Runs remaining steps of a running playbook.
 */
export async function runPlaybookSteps(
  executionId: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  // 1. Fetch execution & steps
  const { data: execution } = await supabase
    .from("playbook_executions")
    .select("*")
    .eq("id", executionId)
    .single();

  if (!execution || execution.status !== "running") {
    return { success: false, error: "Playbook is not in running state" };
  }

  const { data: steps } = await supabase
    .from("playbook_steps")
    .select("*")
    .eq("playbook_id", execution.playbook_id)
    .order("step_number", { ascending: true });

  const stepsList = steps || [];
  let currentStepNum = execution.current_step || 1;
  const createdTasks: string[] = execution.tasks_created || [];

  for (let i = currentStepNum - 1; i < stepsList.length; i++) {
    const step = stepsList[i];
    const config = (step.config || {}) as PlaybookStepConfig;

    if (step.action_type === "generate_task") {
      // Create operational task
      const { data: task } = await supabase
        .from("tasks")
        .insert({
          title: config.title || `Playbook Action: ${config.description || 'Task'}`,
          description: `Automatically generated by Playbook step #${step.step_number}. Config: ${JSON.stringify(config)}`,
          status: "pending",
          priority: "high",
          source: "playbook",
          source_id: executionId,
          approval_required: false
        })
        .select("id")
        .single();

      if (task?.id) {
        createdTasks.push(task.id);
      }
    } 
    else if (step.action_type === "request_approval") {
      // Pause execution, request CEO approval
      await supabase
        .from("playbook_executions")
        .update({
          status: "pending_approval",
          current_step: step.step_number,
          tasks_created: createdTasks,
          updated_at: new Date().toISOString()
        })
        .eq("id", executionId);

      // Create a task for the CEO
      await supabase.from("tasks").insert({
        title: `CEO Decision: Approve ${config.description || 'Playbook Step'}`,
        description: `Playbook execution #${executionId} requires approval to proceed to step #${step.step_number}.`,
        status: "pending",
        priority: "high",
        source: "playbook",
        source_id: executionId,
        approval_required: true
      });

      return { success: true }; // Pause here
    }
    else if (step.action_type === "trigger_api") {
      // External API call implementation hook
      console.log(`[PLAYBOOK API TRIGGER] ${config.endpoint}: ${config.description}`);
    }
    else if (step.action_type === "generate_recommendation") {
      // Generate decision engine recommendation
      await supabase.from("decision_recommendations").insert({
        title: `Playbook Recommendation: ${config.description || "Action"}`,
        description: `Optimize operations based on playbook trigger context.`,
        rationale: `Execution of playbook step #${step.step_number}.`,
        impact_score: 80,
        confidence_score: 90,
        effort_score: 40,
        expected_revenue: 2500.00,
        priority_score: 1.8,
        status: "pending"
      });
    }

    currentStepNum = step.step_number + 1;
  }

  // If we reach here, all steps finished successfully!
  await supabase
    .from("playbook_executions")
    .update({
      status: "completed",
      current_step: stepsList.length,
      tasks_created: createdTasks,
      actual_outcome: "SOP steps executed successfully.",
      success_score: 100.00, // default if completed successfully without metrics overrides
      updated_at: new Date().toISOString()
    })
    .eq("id", executionId);

  await publishEvent("PLAYBOOK_COMPLETED", "playbook_execution", executionId, {
    playbook_id: execution.playbook_id,
    success_score: 100.00
  }, "operations");

  return { success: true };
}

/**
 * Closes playbook execution, evaluates the dynamic success score, and records outcome logs.
 */
export async function completePlaybookExecution(
  executionId: string,
  expectedResultValue: number,
  actualResultValue: number,
  actualOutcomeStr: string
): Promise<{ success: boolean; successScore: number; error?: string }> {
  const supabase = await createClient();

  // 1. Calculate success score capped at 100%
  const score = expectedResultValue > 0 
    ? Math.min(100.00, Number(((actualResultValue / expectedResultValue) * 100).toFixed(2)))
    : 100.00;

  // 2. Update execution
  const { error: updateErr } = await supabase
    .from("playbook_executions")
    .update({
      status: "completed",
      actual_outcome: actualOutcomeStr,
      success_score: score,
      updated_at: new Date().toISOString()
    })
    .eq("id", executionId);

  if (updateErr) {
    return { success: false, successScore: score, error: updateErr.message };
  }

  // 3. Log in decision_outcomes for CEO strategic audits
  try {
    await supabase.from("decision_outcomes").insert({
      expected_result: `Target value: ${expectedResultValue}`,
      actual_result: `Actual achieved: ${actualResultValue}`,
      variance: `Deficit/Surplus: ${actualResultValue - expectedResultValue}`,
      success_score: score
    });
  } catch (e) {
    // Graceful degradation
  }

  await publishEvent("PLAYBOOK_OUTCOME_LOGGED", "playbook_execution", executionId, {
    success_score: score,
    actual_outcome: actualOutcomeStr
  }, "operations");

  return { success: true, successScore: score };
}
